### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by albertma-evotec** [undeadpixel/reinvent-scaffold-decorator#2]
Just a couple of more questions. 
I have run the sample_decorator.py on my trained model (using one given scaffold) but it output more than hundreds of files, each contains only ~2-3 SMILES. 
![image](https://user-images.githubusercontent.com/54853041/73850257-46606880-4823-11ea-924b-83883d031c27.png)

Is it normal that it creates that many files? Just a suggestion, i think it would be convenient if they are all packed in a single file.

Thanks
Albert

**Comment by undeadpixel** [comment]
Hi Albert,

Yes, the output folder is in parquet format. It needs to be opened using [spark](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=parquet#pyspark.sql.DataFrameReader.parquet) or [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html).

If you open it as a parquet you will have all the data as a table with plenty of additional information :smile:.

Spark is already in the environment.yml file, so it's only matter to create a script that opens it and extracts the data that you need.

Hope it helps!

Josep

**Comment by albertma-evotec** [comment]
Thanks Josep. It seems pandas does not support reading the parquet folder or single file directly.

`pd.read_parquet(file_or_dir_path)`

I got this error message.

> ArrowNotImplementedError: Reading lists of structs from Parquet files not yet supported: key_value: list<key_value: struct<key: int32 not null, value: string> not null> not null

But it is OK now, I managed to just convert the results to a pandas dataframe (which I am more familiar with) by 
`pandas_df = results_df.select("*").toPandas()` in the code

and save as .csv which contains all the generated structures.

Hope this help someone who is not familiar with the parquet format like me.
Albert

**Comment by undeadpixel** [comment]
Hi Albert,

I have updated the script to output either a parquet (by default) or a csv file. It is already available. Notice that I have updated the environment.yml, as there were some incompatibilities with latest versions of some packages. Now it should be better.

Thanks for the suggestion!

Josep
