### ISSUE TITLE
sample_scaffolds.py error

### ISSUE THREAD

**Issue by joseteofilo** [undeadpixel/reinvent-scaffold-decorator#3]
Hi,

I'm trying to run the sample_scaffolds.py using the example in README.md. However, I got this error:

Traceback (most recent call last):
  File "./sample_scaffolds.py", line 14, in <module>
    import models.actions as ma
  File "/home/joseteofilo/Documents/reinvent-scaffold-decorator-master/models/actions.py", line 103
    loss = self.model.likelihood(*scaffold_batch, *decorator_batch).mean()
                                                  ^
SyntaxError: invalid syntax

could you help me?

Thanks
José Teófilo

**Comment by undeadpixel** [comment]
Hi!

Are you using the correct conda environment with python 3.6? This looks like an error coming from the fact you are maybe using Python 2 or something similar.

I just tried out the scripts again and regenerating the conda environment and everything works as expected. I would recommend to update conda, delete and reinstall the conda environment and be sure that it is well activated. Also check if the file has been correctly cloned from the repository or some strange character got in there...

Just reopen the issue if you have any more problem or find any way to replicate the bug :smile:.

Best,

Josep
